name: test
on:
  push:
    branches:
      - master
      - github-actions
    paths:
      - '**.go'
  pull_request:
    branches:
      - master
    paths:
      - '**.go'
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.15.x]
        platform: ubuntu-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: go build
      - name: Test
        run: make test
