name: test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.x'
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install go1.16 beta
        run: go get golang.org/dl/go1.16beta1
      - name: Test
        run: make test
